services:
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - .:/app:cached
      - ./docker/nginx/templates:/etc/nginx/templates
  mysql:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db-data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:4.0.4-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
      RABBITMQ_DEFAULT_VHOST: app
  php-cli:
    restart: unless-stopped
    depends_on:
      - mysql
    build:
      context: .
      target: prod
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./supervisor-consumers.conf:/etc/supervisor/conf.d/supervisor-consumers.conf
  php-fpm:
    restart: unless-stopped
    depends_on:
      - mysql
    build:
      context: .
      target: prod
      dockerfile: docker/php-fpm/Dockerfile

volumes:
  db-data: